# Generated by Django 4.2.2 on 2023-06-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Titre',
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.FloatField(default=2.3, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default="it's okay", max_length=100),
            preserve_default=False,
        ),
    ]
