# Generated by Django 4.2.2 on 2023-06-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_band_like_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='like_alors_on_danse',
            field=models.BooleanField(default=False),
        ),
    ]
