# Generated by Django 4.2.2 on 2023-06-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_band_like_alors_on_danse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_alors_on_danse',
        ),
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
